### ISSUE TITLE
a tiny flaw

### ISSUE THREAD

**Issue by chuanwang66** [skywind3000/mini3d#2]
这3行会导致primtive triangle只要有部分与投影平面相交，就被整个裁剪掉。点击↑↓键使立方体靠近投影平面可以复现。
if (transform_check_cvv(&c1) != 0) return;
if (transform_check_cvv(&c2) != 0) return;
if (transform_check_cvv(&c3) != 0) return;

**Comment by skywind3000** [comment]
对，以前的游戏都是这么做的，是一个简易做法。完整做法是三个顶点任何一个超出cvv救需要裁剪成一个或者两个新的三角形，否则就乱套了，比如后面归一化，/w或者/z就会分母为零了。
